# App Name
spring.application.name=Smart_canteen

# ===============================
# DATABASE (Render PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d6tbmk7gi27c73dj2vlg-a:5432/smart_canteen_tq2k
spring.datasource.username=smart_canteen_tq2k_user
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# RENDER PORT
# ===============================
server.port=${PORT:8080}

# ===============================
# THYMELEAF
# ===============================
spring.thymeleaf.cache=false

# ===============================
# EMAIL (BREVO SMTP)
# ===============================
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_SMTP_USERNAME}
spring.mail.password=${BREVO_SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true