

spring.application.name=Smart_canteen

# PostgreSQL (Render)
spring.datasource.url=jdbc:postgresql://dpg-d6tbmk7gi27c73dj2vlg-a:5432/smart_canteen_tq2k
spring.datasource.username=smart_canteen_tq2k_user
spring.datasource.password=XK4ZsylvcfOmLTCsGXLppRWyivoOVgDt

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# IMPORTANT (Render)
server.port=${PORT:8080}

# Thymeleaf
spring.thymeleaf.cache=false


# EMAIL CONFIG (GMAIL)
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true