#spring.application.name=Smart_canteen
## Datasource
#spring.datasource.url=jdbc:mysql://localhost:3306/smart_canteen?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=Avm 1050
#
## JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
## Thymeleaf cache off for development
#spring.thymeleaf.cache=false
#
##for otp purpose
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=swathikottakota02@gmail.com
#spring.mail.password=mfxpegrclwueqlkh
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

spring.application.name=Smart_canteen

# PostgreSQL (Render)
spring.datasource.url=jdbc:postgresql://dpg-d6tbmk7gi27c73dj2vlg-a:5432/smart_canteen_tq2k
spring.datasource.username=smart_canteen_tq2k_user
spring.datasource.password=YOUR_PASSWORD_HERE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# IMPORTANT (Render)
server.port=${PORT:8080}

# Thymeleaf
spring.thymeleaf.cache=false